name: CMake

on:
  pull_request:
    branches: [ "master" ]

  # Allows manual triggering with the "Run workflow" button
  workflow_dispatch:

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Get latest CMake and Ninja
      uses: lukka/get-cmake@latest
      with:
        cmakeVersion: latestrc

    - name: Configure CMake
      run: >
        cmake
        -H.
        -B${{ github.workspace }}/build
        -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }}

    - name: Build Project
      run: >
        cmake 
        --build ${{ github.workspace }}/build 
        --config ${{ env.BUILD_TYPE }}
        --parallel 2

    - name: Test Project
      working-directory: ${{ github.workspace }}/build
      run: ctest -C ${{ env.BUILD_TYPE }} --output-on-failure
